#
#    ███╗░░░███╗░█████╗░███╗░░██╗██╗░░██╗██╗░░░██╗███╗░░██╗████████╗
#    ████╗░████║██╔══██╗████╗░██║██║░░██║██║░░░██║████╗░██║╚══██╔══╝
#    ██╔████╔██║███████║██╔██╗██║███████║██║░░░██║██╔██╗██║░░░██║░░░
#    ██║╚██╔╝██║██╔══██║██║╚████║██╔══██║██║░░░██║██║╚████║░░░██║░░░
#    ██║░╚═╝░██║██║░░██║██║░╚███║██║░░██║╚██████╔╝██║░╚███║░░░██║░░░
#    ╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚═╝░╚═════╝░╚═╝░░╚══╝░░░╚═╝░░░
#
#    By: Skarless <3

SpawnWithCompass: true
TracksInNether: true
DropCompassOnDeath: false